import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DOCS_DIR = join(ROOT, 'docs');
const RELEASENOTES_DIR = join(DOCS_DIR, 'guides', 'releasenotes');
const CACHED_CHANGELOG = join(ROOT, 'titanium-sdk-cache', 'CHANGELOG.md');
const SIDEBAR_PATH = join(DOCS_DIR, '.vitepress', 'releasenotes-sidebar.mjs');
const CHANGELOG_URL = 'https://raw.githubusercontent.com/tidev/titanium-sdk/main/CHANGELOG.md';
const VERSION_RE = /^#{1,2} \[(\d+\.\d+\.\d+)\]/;

function parseVersions(content) {
  const lines = content.split('\n');
  const versions = [];
  let currentVersion = null;
  let currentContent = [];

  for (const line of lines) {
    const match = line.match(VERSION_RE);
    if (match) {
      if (currentVersion) {
        versions.push({ version: currentVersion, content: currentContent.join('\n') });
      }
      currentVersion = match[1];
      currentContent = [];
    }
    currentContent.push(line);
  }

  if (currentVersion) {
    versions.push({ version: currentVersion, content: currentContent.join('\n') });
  }

  return versions;
}

function groupByMajor(versions) {
  const groups = {};
  for (const v of versions) {
    const major = v.version.split('.')[0];
    if (!groups[major]) groups[major] = [];
    groups[major].push(v);
  }
  return groups;
}

function stripHeader(content) {
  const lines = content.split('\n');
  // Remove the first line if it matches a version header
  if (lines[0] && VERSION_RE.test(lines[0])) {
    lines.shift();
  }
  return lines.join('\n').trim();
}

function writePage(filePath, title, body) {
  mkdirSync(dirname(filePath), { recursive: true });
  const frontmatter = `---\ntitle: ${title}\n---\n\n`;
  writeFileSync(filePath, frontmatter + body + '\n', 'utf-8');
}

async function run() {
  let changelog;

  // Fetch from GitHub, fall back to local cache
  try {
    const res = await fetch(CHANGELOG_URL);
    if (res.ok) {
      changelog = await res.text();
      console.log('✓ Fetched CHANGELOG.md from GitHub');
    } else {
      throw new Error(`HTTP ${res.status}`);
    }
  } catch (err) {
    if (existsSync(CACHED_CHANGELOG)) {
      changelog = readFileSync(CACHED_CHANGELOG, 'utf-8');
      console.log('⚠ GitHub fetch failed, using local cache');
    } else {
      console.error('✗ Failed to fetch CHANGELOG.md and no local cache found');
      process.exit(1);
    }
  }

  const versions = parseVersions(changelog);
  console.log(`✓ Parsed ${versions.length} versions from CHANGELOG`);

  const groups = groupByMajor(versions);
  const sortedMajors = Object.keys(groups).sort((a, b) => parseInt(b) - parseInt(a));

  // Generate main index page
  const indexBody = '# Release Notes\n\n' +
    sortedMajors.map(m => `- [Release Notes ${m}.x](/guides/releasenotes/${m}.x)`).join('\n');
  writePage(join(RELEASENOTES_DIR, 'index.md'), 'Release Notes', indexBody);
  console.log('✓ Generated guides/releasenotes/index.md');

  // Generate major version pages and individual release pages
  const sidebarItems = [];

  for (const major of sortedMajors) {
    const groupVersions = groups[major].sort((a, b) => {
      const [aMaj, aMin, aPat] = a.version.split('.').map(Number);
      const [bMaj, bMin, bPat] = b.version.split('.').map(Number);
      if (bMaj !== aMaj) return bMaj - aMaj;
      if (bMin !== aMin) return bMin - aMin;
      return bPat - aPat;
    });

    // Major version group page
    const groupTitle = `Release Notes ${major}.x`;
    const groupBody = `# ${groupTitle}\n\n` +
      groupVersions.map(v =>
        `- [Titanium SDK ${v.version}.GA Release Notes](/guides/releasenotes/${v.version})`
      ).join('\n');
    writePage(join(RELEASENOTES_DIR, `${major}.x.md`), groupTitle, groupBody);
    console.log(`  ✓ Generated guides/releasenotes/${major}.x.md`);

    // Individual release pages
    const releaseItems = [];
    for (const v of groupVersions) {
      const releaseTitle = `Titanium SDK ${v.version}.GA`;
      const releaseBody = `# ${releaseTitle}\n\n${stripHeader(v.content)}`;
      writePage(join(RELEASENOTES_DIR, `${v.version}.md`), releaseTitle, releaseBody);
      releaseItems.push({ text: releaseTitle, link: `/guides/releasenotes/${v.version}` });
    }

    sidebarItems.push({
      text: `${major}.x`,
      collapsed: true,
      items: releaseItems,
    });
  }

  // Generate sidebar
  const sidebarContent = `// Auto-generated by releasenotes.mjs — do not edit manually
export default [
  {
    text: 'Release Notes',
    collapsed: false,
    link: '/guides/releasenotes/',
    items: ${JSON.stringify(sidebarItems, null, 2).split('\n').map((line, i) => i === 0 ? line : '  ' + line).join('\n')},
  },
];
`;
  writeFileSync(SIDEBAR_PATH, sidebarContent, 'utf-8');
  console.log('✓ Generated .vitepress/releasenotes-sidebar.mjs');

  console.log(`\n✅ Generated ${versions.length} release pages + ${sortedMajors.length} group pages + index + sidebar`);
}

run().catch(err => {
  console.error('✗ Script failed:', err);
  process.exit(1);
});
